/**
 * mapas.js
 * Traducción de nombres legibles → values del formulario AXA
 * Uso: import { obtenerValor, MAPAS } from './mapas.js';
 */

export const MAPAS = {

  TipoIdentificacion: {
    "Cédula":                      "1",
    "NIT":                         "2",
    "Tarjeta Identidad":           "3",
    "Cédula Extranjería":          "4",
    "Carne Diplomatico":           "6",
    "Salvo Conducto Permanencia":  "7",
    "Permiso Protección Temporal": "9",
  },

  Genero: {
    "Femenino":  "F",
    "Masculino": "M",
  },

  EstadoCivil: {
    "Soltero(a)":   "1",
    "Casado(a)":    "2",
    "Unión Libre":  "3",
    "Separado(a)":  "4",
    "Viudo":        "5",
  },

  CodigoDepartamento: {
    "AMAZONAS":            "91",
    "ANTIOQUIA":           "5",
    "ARAUCA":              "81",
    "ATLANTICO":           "8",
    "BOGOTA D. C.":        "11",
    "BOLIVAR":             "13",
    "BOYACA":              "15",
    "CALDAS":              "17",
    "CAQUETA":             "18",
    "CASANARE":            "85",
    "CAUCA":               "19",
    "CESAR":               "20",
    "CHOCO":               "27",
    "CORDOBA":             "23",
    "CUNDINAMARCA":        "25",
    "GUAINIA":             "94",
    "GUAJIRA":             "44",
    "GUAVIARE":            "95",
    "HUILA":               "41",
    "MAGDALENA":           "47",
    "META":                "50",
    "NARIÑO":              "52",
    "NORTE DE SANTANDER":  "54",
    "PUTUMAYO":            "86",
    "QUINDIO":             "63",
    "RISARALDA":           "66",
    "SAN ANDRES":          "88",
    "SANTANDER":           "68",
    "SUCRE":               "70",
    "TOLIMA":              "73",
    "VALLE":               "76",
    "VAUPES":              "97",
    "VICHADA":             "99",
  },

  TipoSalario: {
    "Básico":   "1",
    "Integral": "2",
  },

  EpsAfiliado: {
    "ALIANSALUD":                                                    "1",
    "AMBUQ EPSS ESS":                                                "244",
    "ANAS WAYUU":                                                    "230",
    "ASEGURADORA DE VIDA COLSEGUROS":                                "11",
    "ASMET SALUD":                                                   "238",
    "ASOCIACION INDIGENA DEL CAUCA":                                 "232",
    "ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDÓ E.S.S. (AMBUQ)":    "239",
    "BARRANQUILLA SANA E.P.S.":                                      "27",
    "BONSALUD S.A.":                                                 "4",
    "CAFAM EPS":                                                     "217",
    "CAFESALUD E.P.S. S.A.":                                         "3",
    "CAJACOPI ATLANTICO":                                            "223",
    "CAJANAL":                                                       "24",
    "CALISALUD E.P.S.":                                              "28",
    "CAPITAL SALUD EPSS SAS":                                        "235",
    "CAPRECOM E.P.S.":                                               "20",
    "CAPRESOCA":                                                     "25",
    "CAPRESOCA EPS":                                                 "228",
    "COLOMBIANA DE SALUD":                                           "210",
    "COLSUBSIDIO EPSS":                                              "224",
    "COMFABOY EPS":                                                  "215",
    "COMFACHOCO":                                                    "225",
    "COMFACOR EPS":                                                  "216",
    "COMFACUNDI":                                                    "222",
    "COMFAMILIAR CARTAGENA EPS":                                     "214",
    "COMFAMILIAR DE LA GUAJIRA":                                     "218",
    "COMFAMILIAR HUILA EPS":                                         "219",
    "COMFAMILIAR NARIÑO EPS":                                        "220",
    "COMFAMILIARES":                                                 "212",
    "COMFAORIENTE":                                                  "41",
    "COMFASUCRE EPS":                                                "221",
    "COMFENALCO VALLE E.P.S.":                                       "12",
    "COMPARTA EPS-S":                                                "241",
    "COMPENSAR E.P.S.":                                              "8",
    "CONGRESO DE LA REPUBLICA":                                      "204",
    "CONVIDA":                                                       "22",
    "COOMEVA E.P.S. SA":                                             "16",
    "COOSALUD ESS":                                                  "237",
    "CORPORANONIMAS":                                                "21",
    "COSMITET LTDA MAGISTER QUINDIO":                                "209",
    "CRUZ BLANCA E.P.S. SA":                                         "23",
    "DEPTO SERVICIO MED Y ODOD EPM":                                 "36",
    "DIR. GENERAL DE SALUD MILITAR":                                 "208",
    "DUSAKAWI":                                                      "229",
    "E.P.S. CONDOR S.A.":                                            "30",
    "E.P.S. DE CALDAS S.A.":                                         "29",
    "E.P.S. FAMISANAR LTDA.":                                        "17",
    "E.P.S. RISARALDA":                                              "19",
    "E.P.S. SALUDCOOP":                                              "13",
    "E.P.S. SANITAS S.A.":                                           "5",
    "ECOOPSOS":                                                      "240",
    "EMDISALUD ESS":                                                 "236",
    "EMPRESAS PUBLICAS DE MEDELLIN ESP":                             "247",
    "EMSSANAR ESS":                                                  "213",
    "EPS COMFENALCO ANTIOQUIA":                                      "9",
    "EPS FAMILIAR DE COLOMBIA":                                      "43",
    "EPS MALLAMAS EPSI":                                             "233",
    "EPS MUTUAL SER":                                                "249",
    "EPSS CONVIDA":                                                  "226",
    "FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES":           "248",
    "FOSYGA":                                                        "111",
    "FUERZAS MILITARES":                                             "202",
    "FUNDACION SALUD MIA EPS":                                       "42",
    "GOLDEN GROUP S.A. EPS":                                         "39",
    "HUMANA VIVIR S.A. E.P.S.":                                      "14",
    "INPEC":                                                         "205",
    "INSTITUTO DE SEGUROS SOCIALES":                                 "6",
    "MANEXKA":                                                       "231",
    "MEDIMAS S.A.S":                                                 "40",
    "MEJOR SALUD":                                                   "211",
    "MULTIMEDICAS SALUD E.P.S. S.A":                                 "38",
    "NO SUMINISTRADA":                                               "999",
    "NUEVA E.P.S. S.A.":                                             "37",
    "PIJAOSALUD EPSI":                                               "234",
    "POLICIA NACIONAL CAJA SUELDOS":                                 "200",
    "RED SALUD ATENCION HUMANA EPS":                                 "35",
    "S.O.S COMFANDI":                                                "206",
    "SALUD COLPATRIA E.P.S.":                                        "15",
    "SALUD TOTAL S.A. E.P.S":                                        "2",
    "SALUDCOLOMBIA E.P.S. S.A.":                                     "34",
    "SALUDVIDA S.A. E.P.S.":                                         "33",
    "SAVIA SALUD EPS":                                               "243",
    "SELVASALUD S.A. E.P.S.":                                        "31",
    "SERV MEDICOS ECOPETROL":                                        "201",
    "SERVICIO OCCIDENTAL DE SALUD":                                  "18",
    "SOLSALUD E.P.S. S.A.":                                          "26",
    "SURA E.P.S":                                                    "10",
    "UNIMEC S.A.":                                                   "7",
    "UNISALUD":                                                      "207",
  },

  AfpAfiliado: {
    "BBVA HORIZONTE":                          "5",
    "CAJA DE PREV. SOC. DE UNICAUCA":          "259",
    "CAJANAL-CAJA NACIONAL DE PREVISIÓN SOCIAL": "258",
    "CAPRECOM-CAJA DE PREVISION SOCIAL":       "254",
    "CAXDAC-CAJA DE PREVENCIÓN SOCIAL":        "252",
    "COLFONDOS":                               "10",
    "COLPENSIONES":                            "6",
    "FONPRECON-FONDO DEL CONGRESO":            "253",
    "ING PENSIONES Y CESANTIAS":               "260",
    "NO SUMINISTRADA":                         "999",
    "OLD MUTUAL PENSIONES Y CESANTIAS":        "300",
    "PENSIONES DE ANTIOQUIA":                  "257",
    "PORVENIR":                                "3",
    "PROTECCION":                              "2",
    "SANTANDER":                               "8",
    "SKANDIA":                                 "19",
  },

  TipoAfiliacion: {
    "Dependiente":                                                        "1",
    "Empleada Domestica":                                                 "2",
    "Aprendices del SENA en etapa lectiva":                               "12",
    "DEPENDIENTE ENTIDADES O UNIVERSIDADES CON REGIMEN ESPECIAL":         "30",
    "INDEPENDIENTE AGREMIADO":                                            "16",
    "Funcionarios publicos sin tope maximo en el IBC":                    "18",
    "Aprendices del SENA en etapa productiva":                            "19",
    "Estudiantes (Regimen especial-Ley 789/2002)":                        "20",
    "Estudiantes de postgrado en salud (Decreto 190 de 1996)":            "21",
    "Profesor":                                                           "22",
    "MADRES COMUNITARIAS":                                                "4",
    "MISIONES DIPLOMATICAS Y CONSULARES EXTRANJEROS NO OBLIGADOS":        "6",
    "COOPERADOS O PRECOOPERATIVAS DE TRABAJO ASOCIADO":                   "31",
    "COTIZANTE MIEMBRO DE LA CARRERA DIPLOMATICA O CONSUL DE UN":         "32",
    "TRABA DEPEN ENTIDAD BENEFICIARIA SGP":                               "47",
    "TRABAJADOR DE TIEMPO PARCIAL DECRETO 2616 DE 2013 AFILIADOS":        "51",
    "AFILIADO PARTICIPE":                                                 "53",
    "AFILIADO PARTICIPE DEPENDIENTE":                                     "55",
    "BENEFICIARIO DEL FONDO DE SOLIDARIDAD PENSIONAL":                    "33",
    "CONCEJAL CON POLIZA DE SALUD":                                       "34",
    "CONCEJAL MUNICIPAL O DISTRITAL QUE PERCIBE HONORANARIOS NO":         "35",
    "CONCEJAL MUNICIPAL O DISTRITAL QUE PERCIBE HONORARIOS NO":           "36",
    "COTIZANTE DEPEND DE EMPLEO DE EMERGENCIA CON DURACION MAYOR":        "44",
    "COTIZANTE DEPEND DE EMPLEO DE EMERGENCIA MENOR A UN MES":            "45",
    "EDIL JUNTA ADMINISTRATIVA LOCAL NO BENEFICIARIO DEL FONSO SO":       "60",
    "BENEFICIARIO PROGRAMA DE REINCORPORACION":                           "61",
    "PERSONAL DE MAGISTERIO":                                             "62",
    "BENEFICIARIO DE PRESTACION HUMANITARIA":                             "63",
    "TRABAJADOR INDEPENDIENTE PENITENCIARIO":                             "64",
    "VOLUNTARIO EN PRIMERA RESPUESTA APORTE SOLO RIESGOS LABORALE":       "67",
  },

  GrupoOcupacion: {
    "AGENTES COMERCIALES Y CORREDORES":                                                                          "219",
    "AGENTES DE LA ADMINISTRACION PUBLICA EN ADUANAS, IMPUESTOS Y AFINES":                                       "230",
    "AGENTES DE LA POLICIA NACIONAL":                                                                            "14",
    "AGRICULTORES, TRABAJADORES FORESTALES Y AGROPECUARIOS":                                                     "317",
    "ALFAREROS, OPERARIOS DE CRISTALERIAS Y AFINES":                                                             "394",
    "ARQUITECTOS, INGENIEROS Y AFINES":                                                                          "86",
    "ARTESANOS DE LA MADERA":                                                                                    "399",
    "ARTESANOS DE LOS TEJIDOS Y BORDADORES":                                                                     "402",
    "ASEADORES, LAVANDEROS Y PLANCHADORES":                                                                      "546",
    "ASISTENTES DE EDUCACION ESPECIAL":                                                                          "204",
    "ASISTENTES DE ENSEÑANZA EN EDUCACION FORMAL (SUPERIOR, MEDIA, BASICA Y PREESCOLAR)":                        "201",
    "ASISTENTES EN TRABAJO SOCIAL Y COMUNITARIO":                                                                "238",
    "ASTROLOGOS, ADIVINADORES, QUIROMANTICOS Y AFINES":                                                          "297",
    "AUXILIARES CONTABLES, ESTADISTICOS, ADMINISTRATIVOS Y AFINES":                                              "255",
    "AUXILIARES DE LA POLICIA NACIONAL":                                                                         "16",
    "AUXILIARES LAICOS DE LOS CULTOS":                                                                           "247",
    "AYUDANTES DE MECANICA":                                                                                     "528",
    "CAJEROS, TAQUILLEROS Y AFINES":                                                                             "269",
    "CATALOGADORES, BIBLIOTECARIOS, DOCUMENTALISTAS Y AFINES":                                                   "133",
    "CONDUCTORES DE VEHICULOS DE MOTOR":                                                                         "514",
    "COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS ADMINISTRATIVOS, COMERCIALES Y DE SERVICIOS DE EMPRESAS PUBLICAS Y PRIVADAS": "56",
    "COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE PRODUCCION Y OPERACIONES DE EMPRESAS PUBLICAS Y PRIVADAS": "64",
    "DIRECTORES DE DEPARTAMENTOS DE PRODUCCION Y OPERACIONES":                                                   "36",
    "DIRECTORES GENERALES, DE REGIONALES , SUCURSALES,OFICINAS Y AFINES DE EMPRESAS PRIVADAS":                   "32",
    "DIRECTORES GENERALES, DE REGIONALES, SUCURSALES, OFICINAS Y AFINES DE LA ADMINISTRACION PUBLICA":           "22",
    "DIRIGENTES Y ADMINISTRADORES DE PARTIDOS POLITICOS, SINDICATOS Y ORGANIZACIONES ESPECIALIZADAS":            "27",
    "EMPLEADOS DE BIBLIOTECAS, SERVICIOS DE CORREO Y AFINES":                                                    "263",
    "EMPLEADOS DE SERVICIOS DE INFORMACION A CLIENTES":                                                          "275",
    "ENCARGADOS DEL REGISTRO DE MATERIALES Y DE TRANSPORTES":                                                    "259",
    "ENSAMBLADORES":                                                                                             "501",
    "ESCRITORES, ARTISTAS CREATIVOS Y EJECUTANTES":                                                              "144",
    "ESPECIALISTAS EN CIENCIAS ECONOMICAS, SOCIALES Y HUMANAS":                                                  "136",
    "ESPECIALISTAS EN ORGANIZACION, ADMINISTRACION DE EMPRESAS, ANALISIS FINANCIERO Y AFINES":                   "124",
    "FISICOS, QUIMICOS Y AFINES":                                                                                "76",
    "HERREROS, HERRAMENTISTAS Y AFINES":                                                                         "368",
    "INSPECTORES DE OBRAS, SEGURIDAD Y SALUD Y CONTROL DE CALIDAD":                                              "180",
    "INSPECTORES DE POLICIA Y DETECTIVES":                                                                       "236",
    "INSTRUCTORES DE EDUCACION NO FORMAL, VOCACIONAL Y AFINES":                                                  "206",
    "JEFES DE COMUNIDADES INDIGENAS, ETNIAS ESPECIALES Y AFINES":                                                "25",
    "LIMPIABOTAS Y OTROS TRABAJADORES CALLEJEROS":                                                               "531",
    "MAQUINISTAS DE VEHICULOS POR RIEL Y AFINES":                                                                "511",
    "MARINEROS DE CUBIERTA Y AFINES":                                                                            "524",
    "MATEMATICOS, ESTADISTICOS Y AFINES":                                                                        "81",
    "MECANICOS DE PRECISION EN METALES Y MATERIALES SIMILARES":                                                  "383",
    "MECANICOS Y AJUSTADORES DE EQUIPOS ELECTRICOS Y ELECTRONICOS":                                              "378",
    "MECANICOS Y AJUSTADORES DE MAQUINAS":                                                                       "373",
    "MEDICOS, PROFESIONALES EN CIENCIAS DE LA SALUD Y AFINES":                                                   "101",
    "MENSAJEROS, PORTEROS, CONSERJES, VIGILANTES Y AFINES":                                                      "533",
    "MIEMBROS DEL PODER EJECUTIVO Y DE LOS CUERPOS LEGISLATIVOS":                                                "20",
    "MODELOS DE MODAS, ARTE Y PUBLICIDAD":                                                                       "306",
    "MOLDEADORES, SOLDADORES, CHAPISTAS, CALDEREROS, MONTADORES DE ESTRUCTURAS METALICAS Y AFINES":              "361",
    "OBREROS DE LA INDUSTRIA MANUFACTURERA":                                                                     "555",
    "OBREROS DE LA MINERIA Y LA CONSTRUCCION":                                                                   "551",
    "OBREROS DEL TRANSPORTE":                                                                                    "558",
    "OBREROS Y PEONES AGROPECUARIOS, FORESTALES, PESQUEROS Y AFINES":                                            "333",
    "OFICIALES DE LA POLICIA NACIONAL":                                                                          "10",
    "OFICIALES DE LAS FUERZAS MILITARES":                                                                        "3",
    "OFICIALES Y OPERARIOS DE LA CONSTRUCCION EN TRABAJOS DE ACABADO Y AFINES":                                  "349",
    "OFICIALES Y OPERARIOS DE LA CONSTRUCCION Y AFINES":                                                         "344",
    "OFICIALES Y OPERARIOS DE LAS ARTES GRAFICAS Y AFINES":                                                      "386",
    "OPERADORES DE CADENAS DE MONTAJE AUTOMATIZADAS, INSTALACIONES MECANICAS Y DE ROBOTS INDUSTRIALES":          "462",
    "OPERADORES DE EQUIPOS OPTICOS Y ELECTRONICOS":                                                              "169",
    "OPERADORES DE INSTALACIONES DE PROCESAMIENTO DE LA MADERA Y DE LA FABRICACION DE PAPEL":                    "445",
    "OPERADORES DE INSTALACIONES DE PROCESAMIENTO DE METALES":                                                   "436",
    "OPERADORES DE INSTALACIONES DE PRODUCCION DE ENERGIA, INCINERADORES, REFRIGERACION Y AFINES":               "456",
    "OPERADORES DE INSTALACIONES DE TRATAMIENTOS QUIMICOS":                                                      "449",
    "OPERADORES DE INSTALACIONES DE VIDRIERIA, CERAMICA Y AFINES":                                               "441",
    "OPERADORES DE INSTALACIONES MINERAS Y DE EXTRACCION Y PROCESAMIENTO DE MINERALES":                          "432",
    "OPERADORES DE MAQUINARIA AGRICOLA MOVIL Y DE OTRAS MAQUINAS MOVILES":                                       "519",
    "OPERADORES DE MAQUINAS DE IMPRENTA, ENCUADERNACION Y FABRICACION DE PRODUCTOS DE PAPEL":                    "478",
    "OPERADORES DE MAQUINAS PARA ELABORAR O PROCESAR ALIMENTOS Y PRODUCTOS AFINES":                              "491",
    "OPERADORES DE MAQUINAS PARA FABRICAR PRODUCTOS DE CAUCHO Y DE PLASTICO":                                    "473",
    "OPERADORES DE MAQUINAS PARA FABRICAR PRODUCTOS DE MADERA":                                                  "476",
    "OPERADORES DE MAQUINAS PARA FABRICAR PRODUCTOS QUIMICOS":                                                   "468",
    "OPERADORES DE MAQUINAS PARA FABRICAR PRODUCTOS TEXTILES Y ARTICULOS DE PIEL Y CUERO":                       "482",
    "OPERADORES DE MAQUINAS PARA TRABAJAR METALES Y PRODUCTOS MINERALES":                                        "465",
    "OPERARIOS DE LA INDUSTRIA EXTRACTIVA":                                                                      "339",
    "OPERARIOS DE LA MADERA":                                                                                    "426",
    "OPERARIOS DE LOS TEXTILES Y DE LA CONFECCION Y AFINES":                                                     "417",
    "OPERARIOS DE PIELES, CUERO Y CALZADO":                                                                      "423",
    "OPERARIOS DEL PROCESAMIENTO DE ALIMENTOS Y AFINES":                                                         "410",
    "OTROS ARTESANOS":                                                                                           "405",
    "OTROS DIRECTORES DE DEPARTAMENTOS, PUBLICOS Y PRIVADOS":                                                    "46",
    "OTROS OPERADORES DE MAQUINAS Y ENSAMBLADORES":                                                              "508",
    "OTROS PROFESIONALES DE LA EDUCACION":                                                                       "118",
    "OTROS TRABAJADORES DE SERVICIOS PERSONALES A PARTICULARES":                                                 "292",
    "PERSONAL AL SERVICIO DIRECTO DE LOS PASAJEROS":                                                             "281",
    "PERSONAL DE LOS SERVICIOS DE PROTECCION Y SEGURIDAD":                                                       "300",
    "PERSONAL DE SERVICIOS DE RESTAURANTES, ALIMENTOS Y BEBIDAS":                                                "285",
    "PERSONAL DOMESTICO":                                                                                        "544",
    "PESCADORES, CAZADORES Y TRAMPEROS":                                                                         "328",
    "PRACTICANTES DE LA MEDICINA TRADICIONAL Y CURANDEROS":                                                      "196",
    "PROFESIONALES DE LA INFORMATICA":                                                                           "84",
    "PROFESIONALES DEL DERECHO":                                                                                 "129",
    "PROFESIONALES EN CIENCIAS BIOLOGICAS Y OTRAS DISCIPLINAS RELATIVAS A LOS SERES ORGANICOS":                  "97",
    "PROFESORES E INSTRUCTORES DE EDUCACION ESPECIAL":                                                           "116",
    "PROFESORES Y DOCENTES EN EDUCACION FORMAL":                                                                 "111",
    "RECOLECTORES DE BASURA Y AFINES":                                                                           "539",
    "REVOCADORES, PINTORES, LIMPIADORES DE FACHADA Y AFINES":                                                    "356",
    "SACERDOTES Y RELIGIOSOS DE DISTINTAS DOCTRINAS":                                                            "150",
    "SECRETARIOS Y OPERADORES DE MAQUINAS DE OFICINA":                                                           "251",
    "SOLDADOS DE LAS FUERZAS MILITARES":                                                                         "7",
    "SUBOFICIALES DE LA POLICIA NACIONAL":                                                                       "12",
    "SUBOFICIALES DE LAS FUERZAS MILITARES":                                                                     "5",
    "TECNICOS EN NAVEGACION MARITIMA Y AERONAUTICA":                                                             "174",
    "TECNICOS EN PROGRAMACION Y CONTROL INFORMATICOS":                                                           "164",
    "TECNICOS Y POSTSECUNDARIOS NO UNIVERSITARIOS EN CIENCIAS BIOLOGICAS, AGRONOMIA, ZOOTECNIA Y AFINES":        "184",
    "TECNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS EN CIENCIAS FISICAS, QUIMICAS E INGENIERIA":                    "154",
    "TECNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE ACTIVIDADES ARTISTICAS, ESPECTACULOS Y DEPORTES": "240",
    "TECNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE LA MEDICINA MODERNA Y LA SALUD (EXCEPTO PERSONAL DE PORTERIA)": "187",
    "TECNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE SERVICIOS DE ADMINISTRACION":                   "224",
    "TECNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES EN OPERACIONES COMERCIALES":                       "211",
    "TRABAJADORES DE LOS CUIDADOS PERSONALES Y AFINES":                                                          "288",
    "TRABAJADORES PECUARIOS, AVICULTORES CRIADORES DE INSECTOS Y AFINES":                                        "323",
    "VENDEDORES AMBULANTES, A DOMICILIO Y AFINES":                                                               "312",
    "VENDEDORES EN QUIOSCOS Y PUESTOS DE MERCADO":                                                               "310",
    "VENDEDORES Y DEMOSTRADORES DE TIENDAS, ALMACENES Y AFINES":                                                 "308",
  },

  ModalidadTrabajo: {
    "PRESENCIAL":                    "01",
    "TELETRABAJO":                   "02",
    "VOLUNTARIADO":                  "03",
    "TRABAJO EN CASA - HOME OFFICE": "04",
    "TRABAJO REMOTO":                "05",
    "TELETRABAJO MÓVIL":             "06",
    "TELETRABAJO SUPLEMENTARIO":     "07",
    "TELETRABAJO AUTÓNOMO":          "08",
  },

  TareaAltoRiesgo: {
    "NO APLICA":                                      "0000001",
    "TRABAJO EN ALTURAS":                             "0000002",
    "ESPACIOS CONFINADOS":                            "0000003",
    "TRABAJO CON EXPOSICIÓN A ALTAS TEMPERATURAS":    "0000004",
    "EXPOSICIÓN A RADIACIONES IONIZANTES":            "0000005",
    "EXPOSICIÓN A SUSTANCIAS COMPROBADAMENTE CANCERÍGENAS": "0000006",
  },

};

/**
 * Convierte un nombre legible al value del select correspondiente.
 * Lanza un error descriptivo si no encuentra el valor.
 *
 * @param {string} campo     - Nombre del campo (ej: "EpsAfiliado")
 * @param {string} nombre    - Texto legible (ej: "SURA E.P.S")
 * @returns {string}         - El value para usar en selectOption
 */
export function obtenerValor(campo, nombre) {
  const mapa = MAPAS[campo];
  if (!mapa) {
    throw new Error(`❌ Campo desconocido: "${campo}". Verifica que esté en MAPAS.`);
  }
  const valor = mapa[nombre];
  if (valor === undefined) {
    const disponibles = Object.keys(mapa).join('\n  - ');
    throw new Error(
      `❌ "${nombre}" no encontrado en el campo "${campo}".\n` +
      `Opciones disponibles:\n  - ${disponibles}`
    );
  }
  return valor;
}

/**
 * Versión segura: en lugar de lanzar error, devuelve null y loguea advertencia.
 * Útil si prefieres que el bot continúe y reporte los errores al final.
 *
 * @param {string} campo
 * @param {string} nombre
 * @returns {string|null}
 */
export function obtenerValorSeguro(campo, nombre) {
  try {
    return obtenerValor(campo, nombre);
  } catch (e) {
    console.warn(e.message);
    return null;
  }
}
